CHORE: add html,assets and style.css
29td/HelloMicroverse pull request #1
Opened 2022-05-24 15:48 UTC by 29td

2022-05-24 16:06 UTC, Munsa1 requested changes
Hi @29td, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights


## Required Changes ♻️
_Check the comments under the review._
- [x] Kindly add a description to your pull request. Click the three-dotted line in the image below to add and edit your description. Descriptions provide information about the changes you introduce to a particular branch.
![image](https://user-images.githubusercontent.com/81932478/170081378-49f799a2-e186-4471-8531-bf43b26d4567.png)

- [ ] Kindly add linters to your project and ensure the linters pass. Linters help us to adhere to industry standards when writing code. [Refer to this link](https://github.com/microverseinc/linters-config/tree/master/html-css)

- [x] Add information about your project and social media and GitHub handles to your readme file to make it more descriptive
![image](https://user-images.githubusercontent.com/81932478/170082411-6ae022ae-f29d-414e-8302-aa77612cc7fa.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-24 21:03 UTC, Kossi-stack requested changes
**Hi @29td,**

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

**To Highlight**

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ Commit messages is meaningful.

**Required Changes ♻️**

 - [x] Please make sure to use [this readme template](https://github.com/microverseinc/readme-template/blob/master/README.md) and please be sure to edit all of the sections to better suit your project.

 _Check the comments under the review for more changes_.

**Optional suggestions**
 - [ ] Kindly edit the PR's title to something more descriptive. it can be "Hello Microverse Project PR or Hello Microverse PR".
 - [ ] Kindly add test.md and node_modules to gitignore file.
 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-24 21:03 UTC, Kossi-stack commented on README.md
> -- LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)
- [x] Kindly remove Author 2 since you are alone on this project.

2022-05-24 21:51 UTC, Ismailco requested changes
### Hi @29td,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️ Used Github Flow
✔️ Work documented professionally

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-24 21:51 UTC, Ismailco commented on README.md
>  ![](https://img.shields.io/badge/Microverse-blueviolet)
- [ ] [OPTIONAL] Linter should be set up correctly for this repository, kindly add the [linters config files using this repo](https://github.com/microverseinc/linters-config)

2022-05-24 21:51 UTC, Ismailco commented on README.md
>  ![](https://img.shields.io/badge/Microverse-blueviolet)
- [ ] [OPTIONAL] This Pull Request should have a summary describing introduced changes in more detail, kindly edit the description so it meets this requirement

2022-05-24 21:51 UTC, Ismailco commented on README.md
>  ![](https://img.shields.io/badge/Microverse-blueviolet)
- [ ] [OPTIONAL] Branch should have a name of a feature or action e.g. ```created_sidebar``` or ```added_comments_section```, you can skip this requirement in this PR but please in future consider implementing this

2022-05-24 21:51 UTC, Ismailco commented on README.md
>  ![](https://img.shields.io/badge/Microverse-blueviolet)
- [ ] [OPTIONAL] There should be a ```.gitignore``` file listing test.md file and node_modules directory in the repo, please add a this into the gitignore file

2022-05-25 02:17 UTC, 29td commented
Hi @Ismailco
Thank you for the feedback and I will make the changes and hope to do the
same in future as well. Will this feedback stop me from continuing with the
next project? Am I granted the opportunity to continue with the next project

On Tue, 24 May 2022, 23:51 ismail courr, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> Hi @29td <https://github.com/29td>,
>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet.
> Highlights
>
> ✔️ Used Github Flow
> ✔️ Work documented professionally
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In README.md
> <https://github.com/29td/HelloMicroverse/pull/1#discussion_r880975447>:
>
> > @@ -1,56 +1,48 @@
>
>  ![](https://img.shields.io/badge/Microverse-blueviolet)
>
>
>
>    - [OPTIONAL] Linter should be set up correctly for this repository,
>    kindly add the linters config files using this repo
>    <https://github.com/microverseinc/linters-config>
>
> ------------------------------
>
> In README.md
> <https://github.com/29td/HelloMicroverse/pull/1#discussion_r880976506>:
>
> > @@ -1,56 +1,48 @@
>
>  ![](https://img.shields.io/badge/Microverse-blueviolet)
>
>
>
>    - [OPTIONAL] This Pull Request should have a summary describing
>    introduced changes in more detail, kindly edit the description so it meets
>    this requirement
>
> ------------------------------
>
> In README.md
> <https://github.com/29td/HelloMicroverse/pull/1#discussion_r880978311>:
>
> > @@ -1,56 +1,48 @@
>
>  ![](https://img.shields.io/badge/Microverse-blueviolet)
>
>
>
>    - [OPTIONAL] Branch should have a name of a feature or action e.g.
>    created_sidebar or added_comments_section, you can skip this
>    requirement in this PR but please in future consider implementing this
>
> ------------------------------
>
> In README.md
> <https://github.com/29td/HelloMicroverse/pull/1#discussion_r880979177>:
>
> > @@ -1,56 +1,48 @@
>
>  ![](https://img.shields.io/badge/Microverse-blueviolet)
>
>
>
>    - [OPTIONAL] There should be a .gitignore file listing test.md file
>    and node_modules directory in the repo, please add a this into the
>    gitignore file
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/29td/HelloMicroverse/pull/1#pullrequestreview-983886409>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWFX32AXOFTMXGEDODPGOQLVLVFOPANCNFSM5W2BMIOA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-25 04:19 UTC, Ismailco commented
Hi @29td, if you do the changes and fix the conflicts in this branch then yes you can request another review, and get approved

2022-05-25 08:26 UTC, Davidosky007 reviewed
Hello @29td  👋,

_This is an additional review as a result of the second opinion request._

* Kindly setup your linters properly by following the steps in this link below 👇 as your linter checks are still missing and try to work on the OPTIONAL cahnges in your spare time 🙏 
https://github.com/microverseinc/linters-config/tree/master/html-css 


As this was the only reason that your project was not approved it will be approved as soon as possible.
Please request for another Code review in your dashboard 
Keep rocking 🚀!

2022-05-25 10:20 UTC, closed without merging